apiVersion: v1
kind: ConfigMap
metadata:
  name: vigobas-samtykke-proxy
  namespace: vigobas
data:
  nginx.conf: |
    server {
      listen 80 default_server;
      listen [::]:80 default_server;
      #server_name no;
      #frontend proxy
      location / {
          proxy_pass http://localhost:8000;
          proxy_set_header Connection '';
          proxy_http_version 1.1;
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
      }
      
      #backend proxy
      location /api/ {
          proxy_pass http://localhost:9000;
          proxy_set_header Connection '';
          proxy_http_version 1.1;
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
      }
    }