apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ include "vigobas-samtykke.name" . }}
  name: {{ include "vigobas-samtykke.name" . }}
  namespace: {{ .Values.namespace}}
  annotations:
    operator.1password.io/item-path: {{ .Values.deployment.annotations.onepwitempath}}
    operator.1password.io/item-name: {{ .Values.deployment.annotations.onepwitemname}}
spec:
  replicas: {{ .Values.deployment.replicas}}
  minReadySeconds: {{ .Values.deployment.minReadySeconds}}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit}}
  strategy:
    type: {{ .Values.deployment.strategy.type}}
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.strategy.maxUnavailable}}
      maxSurge: {{ .Values.deployment.strategy.maxSurge}}
  selector:
    matchLabels:
      io.kompose.service: {{ include "vigobas-samtykke.name" . }}
  template:
    metadata:
      labels:
        io.kompose.service: {{ include "vigobas-samtykke.name" . }}
    spec:
      restartPolicy: {{ .Values.deployment.template.spec.restartPolicy}}
      volumes:
        - name: {{ .Values.deployment.template.spec.volumes.name}}
          configMap:
            name: {{ .Values.deployment.template.spec.volumes.configMap.name}}
      containers:
      - name: frontend
        image: {{ .Values.frontend.image}}
        ports:
        - containerPort: {{ .Values.frontend.containerPort}}
        resources:
          limits:
            cpu: {{ .Values.frontend.limits.cpu}}
            memory: {{ .Values.frontend.limits.memory}}
          requests:
            cpu: {{  .Values.frontend.requests.cpu}}
            memory: {{ .Values.frontend.requests.memory}}
      - name: backend
        image: {{ .Values.backend.image}}
        envFrom:
        - secretRef:
            name: {{ .Values.backend.secretRef.name}}
        env:
          {{- range .Values.backend.env }}
          - {name: {{ .name}}, value: {{ .value | toJson}}}
          {{- end }}
        ports:
        - containerPort: {{ .Values.backend.containerPort}}
        resources:
          limits:
            cpu: {{ .Values.backend.limits.cpu}}
            memory: {{ .Values.backend.limits.memory}}
          requests:
            cpu: {{ .Values.backend.requests.cpu}}
            memory: {{ .Values.backend.requests.memory}}
        readinessProbe:
          httpGet:
            path: {{ .Values.backend.readinessProbe.path}}
            port: {{ .Values.backend.readinessProbe.port}}
          timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds}}
      - name: proxy
        image: {{ .Values.proxy.image}}
        resources:
          limits:
            cpu: {{ .Values.proxy.limits.cpu}}
            memory: {{ .Values.proxy.limits.memory}}
        env:
          {{- range .Values.proxy.env }}
          - {name: {{ .name}}, value: {{ .value | toJson}}}
          {{- end }}
        ports:
        - containerPort: {{ .Values.proxy.containerPort}}
        volumeMounts:
          - mountPath: {{ .Values.proxy.volumeMounts.mountPath}}
            name: {{ .Values.proxy.volumeMounts.name}}