{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "fint-core-explorer.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fint-core-explorer.fullname" . }}
rules:
  - verbs: ["get", "watch", "list"]
    apiGroups:
      - '*'
    resources:
      - '*'
{{- end -}}