{{- if .Values.configmap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-kunde-portal
data:
  nginx.conf: |
    server {
      listen 80 default_server;
      listen [::]:80 default_server;
      server_name kunde-beta.felleskomponent.no;
      location / {
          proxy_pass http://localhost:8000;
          proxy_set_header Connection '';
          proxy_http_version 1.1;
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
      }
      location /api/ {
          proxy_pass http://localhost:8080;
          proxy_set_header Connection '';
          proxy_http_version 1.1;
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
      }
      location /actuator/prometheus {
          proxy_pass http://localhost:8080;
          proxy_set_header Connection '';
          proxy_http_version 1.1;
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
          proxy_set_header x-nin 0;
      }
      location ~ /api/tests/[^/]+/links {
          proxy_pass http://localhost:8081;
          proxy_set_header Connection '';
          proxy_http_version 1.1;
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
      }
      location /api/tests/ {
          proxy_pass http://localhost:8082;
          proxy_set_header Connection '';
          proxy_http_version 1.1;
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
      }
      location /tickets {
           proxy_pass http://localhost:8083;
           proxy_set_header Connection '';
           proxy_http_version 1.1;
           chunked_transfer_encoding off;
           proxy_buffering off;
           proxy_cache off;
       }
    }
{{- end }}