apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fint-kundeportal.name" . }}
  labels:
    {{- include "fint-kundeportal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fint-kundeportal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fint-kundeportal.selectorLabels" . | nindent 8 }}
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8  }}
      {{- end }}
      containers:
        - name: {{ include "fint-kundeportal.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              port: {{ .Values.service.port }}
              path: /actuator/health
          readinessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.timeoutSeconds }}
            httpGet:
              port: {{ .Values.service.port }}
              path: /actuator/health
              httpHeaders:
                - name: x-nin
                  value: '0'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
          {{- toYaml .Values.envFrom | nindent 12 }}
          env: 
            {{- if .Values.env }}
                {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
        {{- if .Values.nginx.create -}}
        - name: {{ .Values.nginx.name }}
          image: {{ .Values.nginx.image }}
          resources:
          {{- toYaml .Values.nginx.resources | nindent 12 }}
          env:
            {{- range .Values.nginx.env }}
            - {name: {{ .name}}, value: {{ .value | toJson}}}
            {{- end }}
          ports:
            - containerPort: {{ .Values.nginx.containerPort }}
          {{- with .Values.nginx.volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12  }}
          {{- end }}
         {{- end }}
        {{- if .Values.frontend.create -}}
        - name: {{ .Values.frontend.name }}
          image: {{ .Values.frontend.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
          {{- toYaml .Values.frontend.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          env:
            {{- range .Values.frontend.env }}
            - {name: {{ .name}}, value: {{ .value | toJson}}}
            {{- end }}  
        {{- end }}
        {{- if .Values.test_runner.create -}}
        - name: {{ .Values.test_runner.name }}
          image: {{ .Values.test_runner.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
          {{- toYaml .Values.test_runner.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.test_runner.containerPort }}
          envFrom:
          {{- toYaml .Values.test_runner.envFrom | nindent 12 }}
          env:
            {{- range .Values.test_runner.env }}
            - {name: {{ .name}}, value: {{ .value | toJson}}}
            {{- end }}
        {{- end }}
        {{- if .Values.link_walker.create -}}
        - name: {{ .Values.link_walker.name }}
          image: {{ .Values.link_walker.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
          {{- toYaml .Values.link_walker.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.link_walker.containerPort }}
          envFrom:
          {{- toYaml .Values.link_walker.envFrom | nindent 12 }}
          env:
            {{- range .Values.link_walker.env }}
            - {name: {{ .name}}, value: {{ .value | toJson}}}
            {{- end }}
        {{- end }}
        {{- if .Values.zendesk_integration.create -}}
        - name: {{ .Values.zendesk_integration.name }}
          image: {{ .Values.zendesk_integration.image }}
          resources:
          {{- toYaml .Values.zendesk_integration.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.zendesk_integration.containerPort }}
          envFrom:
          {{- toYaml .Values.zendesk_integration.envFrom | nindent 12 }}
          env:
            {{- range .Values.zendesk_integration.env }}
            - {name: {{ .name}}, value: {{ .value | toJson}}}
            {{- end }}
        {{- end }}