apiVersion: v1
kind: Pod
metadata:
  name: {{ include "fint-kundeportal.name" . }}
spec:
  containers:
    - name: kunde-portal
        image: fintlabsacr.azurecr.io/kunde-portal:build.${BUILD_NUMBER}_${GIT_COMMIT}
        ports:
        - containerPort: 8080
            protocol: TCP
        envFrom:
            - secretRef:
                name: fint-portal-user
        env:
        - name: TZ
            value: Europe/Oslo
        - name: fint.client-config.test-service-base-url
            value: ""
        - name: fint.client-config.linkwalker-base-url
            value: ""
        - name: logging.level.no.fint.portal.security
            value: debug
        - name: fint.unleash.api
            value: http://unleash-server:4242/api/
        resources:
            limits:
            cpu: "2"
            memory: "2Gi"
            requests:
            cpu: "250m"
            memory: "1Gi"
        readinessProbe:
            httpGet:
            path: /actuator/health
            port: 8080
            httpHeaders:
                - name: x-nin
                value: '0'
            initialDelaySeconds: 30
            timeoutSeconds: 5
    - name: nginx
        image: nginx:1.15.10
        resources:
            limits:
            cpu: "500m"
            memory: "128Mi"
        env:
            - name: TZ
            value: Europe/Oslo
        ports:
            - containerPort: 80
        volumeMounts:
            - mountPath: /etc/nginx/conf.d
            name: nginx-kunde-portal
        - name: frontend
        image: fintlabsacr.azurecr.io/kunde-portal-frontend:latest
        imagePullPolicy: Always
        resources:
            limits:
            cpu: 500m
            memory: 128Mi
        ports:
            - containerPort: 8000
        env:
            - name: TZ
            value: Europe/Oslo
    - name: test-runner
        image: fintlabsacr.azurecr.io/test-runner:latest
        imagePullPolicy: Always
        resources:
            limits:
            cpu: "2"
            memory: "2Gi"
            requests:
            cpu: "250m"
            memory: "1Gi"
        ports:
            - containerPort: 8082
        envFrom:
            - secretRef:
                name: fint-portal-user
        env:
            - name: server.port
            value: "8082"
    - name: link-walker
        image: fintlabsacr.azurecr.io/link-walker:latest
        imagePullPolicy: Always
        resources:
            limits:
            cpu: "2"
            memory: "4Gi"
            requests:
            cpu: "250m"
            memory: "3Gi"
        ports:
            - containerPort: 8081
        envFrom:
            - secretRef:
                name: fint-portal-user
        env:
            - name: TZ
            value: Europe/Oslo
            - name: JAVA_TOOL_OPTIONS
            value: '-XX:+ExitOnOutOfMemoryError -Xmx3G -verbose:gc'
            - name: server.port
            value: "8081"
            - name: fint.rest-template.provider
            value: portal-api
    - name: zendesk-integration
        image: fintlabsacr.azurecr.io/zendesk-integration:PR-19.10
        resources:
            limits:
            cpu: "2"
            memory: "2Gi"
            requests:
            cpu: "250m"
            memory: "1Gi"
        ports:
            - containerPort: 8083
        envFrom:
            - secretRef:
                name: fint-portal-user
            - secretRef:
                name: zendesk-integration
        env:
            - name: logging.level.no.fint.provisioning
            value: debug
            - name: fint.webclient.connection-provider.type
            value: NEW
            - name: fint.zendesk.timeout
            value: PT10S
            - name: TZ
            value: Europe/Oslo
            - name: fint.zendesk.prov.user.queuing.delay
            value: "600000"
            - name: server.port
            value: "8083"