apiVersion: v1
kind: Service
metadata:
  name: {{ include "fint-kundeportal.fullname" . }}
  labels:
    {{- include "fint-kundeportal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fint-kundeportal.selectorLabels" . | nindent 4 }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "fint-kundeportal.name" . }}
  labels:
    {{- include "fint-kundeportal.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
      {{- toYaml . | nindent 4  }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "fint-kundeportal.labels" . | nindent 4 }}