# Default values for fint-sikri-arkiv-adapter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: 

onePasswordItem: 
  name: 
  create: false

environment:

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

volumes:
  - name: tempdir
    emptyDir:
      sizeLimit: 1G
volumeMounts:
  - name: tempdir
    mountPath: /temp

image:
  repository: fintlabsacr.azurecr.io/sikri-arkiv-adapter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag:

containerPort: 8091

secretRef:
  name:

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  limits:
      memory: "2Gi"
      cpu: "2"
  requests:
    memory: "1Gi"
    cpu: "250m"

env:
  - {name: TZ, value: Europe/Oslo}
  - name: JAVA_TOOL_OPTIONS
    value: >-
      -Xmx1G -verbose:gc
      -XX:+ExitOnOutOfMemoryError
      -Dfile.encoding=UTF-8
      -Dcom.sun.xml.ws.transport.http.client.HttpTransportPipe.dump=true
      -Dcom.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.dump=true
      -Dcom.sun.xml.ws.transport.http.HttpAdapter.dump=true
      -Dcom.sun.xml.internal.ws.transport.http.HttpAdapter.dump=true
      -Dcom.sun.xml.internal.ws.transport.http.HttpAdapter.dumpTreshold=10000
      -Dcom.sun.security.enableAIAcaIssuers=true