apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fint-visma-betaling-adapter.name" . }}
  labels:
    {{- include "fint-visma-betaling-adapter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fint-visma-betaling-adapter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fint-visma-betaling-adapter.selectorLabels" . | nindent 8 }}
    {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ include "fint-visma-betaling-adapter.name" . }}
          securityContext:
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.timeoutSeconds }}
            httpGet:
              path: /
              port: http
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapRef }}
            - secretRef:
                name: {{ .Values.secretRef }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range .Values.env }}
            - {name: {{ .name}}, value: {{ .value | toJson}}}
            {{- end }}