{{- define "lib-chart.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "lib-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lib-chart.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "lib-chart.selectorLabels" . | nindent 8 }}
      {{- with .Values.annotations }}
      annotations:
      {{- end }}
    spec:
      {{- with .Values.restartPolicy }}
      restartPolicy:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8  }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.name  | quote | default "http" }}
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12  }}
          {{- end }}
          readinessProbe:
            initialDelaySeconds: {{.Values.initialDelaySeconds }}
            timeoutSeconds: {{.Values.timeoutSeconds }}
            httpGet:
              port: {{ .Values.service.port }}
              path: {{ .Values.httpGetPath | default "/" }}
              {{- with .Values.httpHeaders }}
              httpHeaders:
              {{- toYaml . | nindent 14  }}
              {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12  }}
          {{- end }}
          envFrom:
          {{- toYaml .Values.envFrom | nindent 12 }}
          env: 
            {{- if .Values.env }}
                {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
{{- end }}