{{- define "lib-chart.onePasswordItem" -}}
{{- if .Values.onePasswordItem.create -}}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Release.Name }}
  labels:
spec:
  itemPath: "vaults/aks-{{ required "Need to define environment!" .Values.environment }}-vault/items/{{ .Values.onePasswordItem.name }}"
{{- end }}
{{- end }}