{{- define "lib-chart.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "lib-chart.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
      {{- toYaml . | nindent 4  }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- with .Values.service.selector }}
  selector:
      {{- toYaml . | nindent 4  }}
  {{- end }}
{{- end }}