apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
 name: fint-audit-web-eventhub
 labels:
spec:
 itemPath: {{ include "fint-core-stack.onePasswordVaultPath" . }}/"fint-audit-web-eventhub"