apiVersion: v1
kind: Service
metadata:
  annotations: {service.beta.kubernetes.io/azure-load-balancer-internal: 'true'}
  labels: 
    fint.stack: {{ include "fint-core-stack.name" . }}
    fint.role: provider
    {{- include "fint-core-stack.labels" . | nindent 4 }}
  name: provider-{{ include "fint-core-stack.name" . }}
spec:
  type: LoadBalancer
  ports:
    - {name: {{ .Values.provider.service.port | quote}}, port: {{ .Values.provider.service.port }}}
  selector: {fint.stack: {{ include "fint-core-stack.name" . }}, fint.role: provider}