{{- if .Values.thumbor.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fint.service: thumbor
  name: thumbor
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      fint.service: thumbor
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        fint.service: thumbor
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/Oslo
        image: fintlabsacr.azurecr.io/thumbor:6.5.2-3
        imagePullPolicy: IfNotPresent
        name: thumbor
        ports:
        - containerPort: 8888
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 8888
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 128Mi
        volumeMounts:
        - mountPath: /tmp/thumbor/storage
          name: cache
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: cache
{{ end }}