# Default values for fint-graphql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
minReadySeconds: 30
revisionHistoryLimit: 10
progressDeadlineSeconds: 60

onePasswordItem: 
  name: fint-portal-user-kundeportal
  create: false

onePasswordItemZendeskIntegration: 
  name: zendesk-integration
  create: false

configmap:
  create: false

image:
  repository: fintlabsacr.azurecr.io/kunde-selvregistrering
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: e69d317

imagePullSecrets: []
nameOverride: kunde-selvregistrering
fullnameOverride: ""

annotations:


labels:
  io.kompose.service: kunde-selvregistrering

initialDelaySeconds: 30
timeoutSeconds: 5

strategy:
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

selector:
  io.kompose.service: kunde-selvregistrering

envFrom:
  - configMapRef:
      name: fint-environment
  - secretRef:
      name: fint-portal-user

containerPort: 8080

volumes:


service:
  name:
  type: LoadBalancer
  port: 8080
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  selector:
    io.kompose.service: fint-kunde-selvregistrering

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: "2"
    memory: "2Gi"
  requests:
    cpu: "250m"
    memory: "1Gi"

env:

nginx:
  create: false 

frontend:
  create: false 

test_runner:
  create: false 

link_walker:
  create: false 

zendesk_integration:
  create: false 