# Default values for fint-graphql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
minReadySeconds: 30
revisionHistoryLimit: 10
progressDeadlineSeconds: 600

image:
  repository: fintlabsacr.azurecr.io/kunde-portal
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: build.178_fdcba05025496b6e94436b4e2b8da7d92acc6292

imagePullSecrets: []
nameOverride:
fullnameOverride: ""

configmap:
  create: true
 
onePasswordItem: 
  name: fint-portal-user-kundeportal
  create: true

onePasswordItemZendeskIntegration: 
  name: zendesk-integration
  create: true

environment: beta


annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "80"
  prometheus.io/path: "/actuator/prometheus"

labels:
  io.kompose.service: fint-kunde-portal

initialDelaySeconds: 30
timeoutSeconds: 5

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

selector:
  io.kompose.service: fint-kunde-portal

envFrom:
  - secretRef: 
      name: fint-portal-user-kundeportal

containerPort: 8080

volumes:
  - name: nginx-kunde-portal
    configMap:
      name: nginx-kunde-portal

service:
  name: "80"
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  selector:
    io.kompose.service: fint-kunde-portal

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: "2"
    memory: "2Gi"
  requests:
    cpu: "250m"
    memory: "1Gi"

env:
  - name: TZ
    value: Europe/Oslo
  - name: fint.client-config.test-service-base-url
    value: ""
  - name: fint.client-config.linkwalker-base-url
    value: ""
  - name: logging.level.no.fint.portal.security
    value: debug
  - name: fint.unleash.api
    value: http://unleash-server:4242/api/

nginx:
  create: true 
  name: nginx
  image: nginx:1.15.10
  resources:
    limits:
      cpu: "500m"
      memory: "128Mi"
  env:
    - name: TZ
      value: Europe/Oslo
  containerPort: 80
  volumeMounts:
    - mountPath: /etc/nginx/conf.d
      name: nginx-kunde-portal

frontend:
  create: true
  name: frontend
  image: fintlabsacr.azurecr.io/kunde-portal-frontend:latest
  imagePullPolicy: Always
  resources:
    limits:
      cpu: "500m"
      memory: "128Mi"
  containerPort: 8000
  env:
    - name: TZ
      value: Europe/Oslo
  
test_runner:
  create: true
  name: test-runner
  image: fintlabsacr.azurecr.io/test-runner:latest
  imagePullPolicy: Always
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
    requests:
      cpu: "250m"
      memory: "1Gi"
  containerPort: 8082
  envFrom:
    - secretRef:
        name: fint-portal-user-kundeportal
  env:
    - name: server.port
      value: "8082"

link_walker:
  create: true
  name: link-walker
  image: fintlabsacr.azurecr.io/link-walker:latest
  imagePullPolicy: Always
  resources:
    limits:
      cpu: "2"
      memory: "4Gi"
    requests:
      cpu: "250m"
      memory: "3Gi"
  containerPort: 8081
  envFrom:
    - secretRef:
        name: fint-portal-user-kundeportal
  env:
    - name: TZ
      value: Europe/Oslo
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx3G -verbose:gc'
    - name: server.port
      value: "8081"
    - name: fint.rest-template.provider
      value: portal-api

zendesk_integration:
  create: true
  name: zendesk-integration
  image: fintlabsacr.azurecr.io/zendesk-integration:PR-19.10
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
    requests:
      cpu: "250m"
      memory: "1Gi"
  containerPort: 8083
  envFrom:
    - secretRef:
        name: fint-portal-user-kundeportal
    - secretRef:
        name: zendesk-integration
  env:
    - name: logging.level.no.fint.provisioning
      value: debug
    - name: fint.webclient.connection-provider.type
      value: NEW
    - name: fint.zendesk.timeout
      value: PT10S
    - name: TZ
      value: Europe/Oslo
    - name: fint.zendesk.prov.user.queuing.delay
      value: "600000"
    - name: server.port
      value: "8083"