apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.nameOverride }}
  template:
    metadata:
    spec:
      volumes:
        - name: tempdir
          emptyDir:
            sizeLimit: 1G
      containers:
        - name: {{ .Values.nameOverride }}
          image: "{{ .Values.image.repository }}"
          #imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range .Values.env }}
            - {name: {{ .name}}, value: {{ .value | toJson}}}
            {{- end }}