apiVersion: v1
kind: Service
metadata:
  name: {{ include "fint-namerator.fullname" . }}
  labels:
    {{- include "fint-namerator.labels" . | nindent 4 }}
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fint-namerator.selectorLabels" . | nindent 4 }}
