{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fint-namerator.serviceAccountName" . }}
  labels:
    {{- include "fint-namerator.labels" . | nindent 4 }}
    {{- toYaml .Values.labels | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fint-namerator.serviceAccountName" . }}
  labels:
    {{- include "fint-namerator.labels" . | nindent 4 }}
    {{- toYaml .Values.labels | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: 
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch      
  - apiGroups: ["fintlabs.no"]
    resources: ["NamOAuthClientApplicationResource"]
    verbs: 
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "fint-namerator.serviceAccountName" . }}
  labels:
    {{- include "fint-namerator.labels" . | nindent 4 }}
    {{- toYaml .Values.labels | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "fint-namerator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "fint-namerator.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
