apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fint-graphql.name" . }}
  labels:
    {{- include "fint-graphql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fint-graphql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fint-graphql.selectorLabels" . | nindent 8 }}
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ include "fint-graphql.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.timeoutSeconds }}
            httpGet:
              path: {{ .Values.httpGetPath }}
              port: {{ .Values.service.port }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.timeoutSeconds }}
            httpGet:
              port: {{ .Values.service.port }}
              path: {{ .Values.httpGetPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapRef }}
          env: 
            {{- if .Values.env }}
                {{- toYaml .Values.env | nindent 12 }}
            {{- end }}