apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fint-oneroster-rest-provider.name" . }}
  labels:
    io.kompose.service: {{ include "fint-oneroster-rest-provider.name" . }}
spec:
  selector:
    matchLabels:
      io.kompose.service: {{ include "fint-oneroster-rest-provider.name" . }}
  template:
    metadata:
      labels:
        io.kompose.service: {{ include "fint-oneroster-rest-provider.name" . }}
    spec:
      containers:
        - name: {{ include "fint-oneroster-rest-provider.name" . }}
          image: {{ .Values.deployment.containers.repo}}/{{ .Values.deployment.containers.image}}:{{ .Values.deployment.containers.tag}}
          resources:
            limits:
              cpu: {{ .Values.deployment.containers.resources.limits.cpu}}
              memory: {{ .Values.deployment.containers.resources.limits.memory}}
            requests:
              cpu: {{ .Values.deployment.containers.resources.requests.cpu}}
              memory: {{ .Values.deployment.containers.resources.requests.memory}}
          ports:
            - containerPort: {{ .Values.deployment.containers.resources.ports.containerPort}}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.containers.resources.readinessProbe.httpGet.path}}
              port: {{ .Values.deployment.containers.resources.readinessProbe.httpGet.port}}
            initialDelaySeconds: {{ .Values.deployment.containers.resources.readinessProbe.initialDelaySeconds}}
            timeoutSeconds: {{ .Values.deployment.containers.resources.readinessProbe.timeoutSeconds}}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.containers.resources.livenessProbe.httpGet.path}}
              port: {{ .Values.deployment.containers.resources.livenessProbe.httpGet.port}}
            initialDelaySeconds: {{ .Values.deployment.containers.resources.livenessProbe.initialDelaySeconds}}
            timeoutSeconds: {{ .Values.deployment.containers.resources.livenessProbe.timeoutSeconds}}
          env:
            {{- range .Values.deployment.containers.env }}
            - {name: {{ .name}}, value: {{ .value }}}
            {{- end }}   