{- if .Values.onePasswordItem.create -}}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "fint-oneroster-rest-provider.name" . }}
  labels:
spec:
  itemPath: "vaults/aks-{{ required "Need to define environment!" .Values.onePasswordItem }}-vault/items/{{ .Values.onePasswordItem }}"


# sjekke denne!!