apiVersion: v1
kind: Service
metadata:
  name: {{ include "fint-oneroster-rest-provider.name" . }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    io.kompose.service: {{ include "fint-oneroster-rest-provider.name" . }}
  

  