version: '3.3'

services:

  master:
    environment: 
      TZ: Europe/Oslo
    build: ./master
    ports: 
      - 8080:8080
      - 50000:50000
    volumes: 
      - jenkins_home:/var/jenkins_home

  slave:
    environment: 
      TZ: Europe/Oslo
    build: ./slave
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    depends_on: 
      - master
    restart: unless-stopped

volumes:
  jenkins_home:
