pipeline {
    agent { label 'docker' }
    stages {
        stage('Build') {
            steps {
                sh "docker build --tag master master"
                sh "docker build --tag slave slave"
            }
        }
        stage('Publish to ACR') {
            when {
                branch 'master'
            }
            steps {
                script {
                    DATE_TAG = java.time.LocalDate.now()
                }
                sh "docker tag master fintlabsacr.azurecr.io/jenkins-master:${DATE_TAG}"
                sh "docker tag slave  fintlabsacr.azurecr.io/jenkins-slave:${DATE_TAG}"
                withDockerRegistry([credentialsId: 'fintlabsacr.azurecr.io', url: 'https://fintlabsacr.azurecr.io']) {
                    sh "docker push fintlabsacr.azurecr.io/jenkins-master:${DATE_TAG}"
                    sh "docker push fintlabsacr.azurecr.io/jenkins-slave:${DATE_TAG}"
                }
            }
        }

    }
}
