#This is an example for a values.file to use for this library

replicaCount: 1
minReadySeconds: 30
revisionHistoryLimit: 10
progressDeadlineSeconds: 600

image:
  repository: fintlabsacr.azurecr.io/kunde-portal
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: kunde-portal
fullnameOverride: ""

annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "80"
  prometheus.io/path: "/actuator/prometheus"

initialDelaySeconds: 30
timeoutSeconds: 5

livenessProbe:
  httpGet:
    path: /
    port: http
  
httpGetPath: /actuator/health

httpHeaders:
  - name: x-nin
    value: '0'

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

restartPolicy: Always

envFrom:
  - secretRef: 
      name: fint-portal-user

containerPort: 8080

volumeMounts:
  - name: credentials
    mountPath: /credentials

volumes:
  - name: nginx-kunde-portal
    configMap:
      name: nginx-kunde-portal

service:
  name: 
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  selector:
    io.kompose.service: fint-kunde-portal

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: "2"
    memory: "2Gi"
  requests:
    cpu: "250m"
    memory: "1Gi"

env:
  - name: TZ
    value: Europe/Oslo
  - name: fint.client-config.test-service-base-url
    value: ""
  - name: fint.client-config.linkwalker-base-url
    value: ""
  - name: logging.level.no.fint.portal.security
    value: debug
  - name: fint.unleash.api
    value: http://unleash-server:4242/api/
