#This is an example for a values.file to use for this library

replicaCount: 5
minReadySeconds: 30
revisionHistoryLimit: 0
progressDeadlineSeconds: 600

image:
  repository: fintlabsacr.azurecr.io/jenkins-slave
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 2021-02-22

imagePullSecrets: []
nameOverride: jenkins-slave
fullnameOverride: ""

annotations:

storageClass:     
  create: false 

serviceAccount:
  # Specifies whether a service account should be created
  create: false 

persistence:
  enabled: false

initialDelaySeconds: 120
timeoutSeconds: 5

securityContext:

securityContextContainer:
  privileged: true

httpHeaders:

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 2
    maxSurge: 2

restartPolicy: Always

envFrom:

containerPort: 
  - name: http
    containerPort: 8080
    protocol: TCP

volumeMounts:
  - name: host-tmp
    mountPath: /tmp

volumes:
  - name: dind-storage
    emptyDir:
      sizeLimit: "10Gi"
  - name: host-tmp
    hostPath:
      path: /tmp

service:
  name: 
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (HEAD)
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  selector:
    io.kompose.service: jenkins-master

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: "2"
    memory: "2Gi"
  requests:
    cpu: "250m"
    memory: "1Gi"

env:
  - name: TZ
    value: Europe/Oslo
  - name: EXECUTORS
    value: "1"
  - name: MASTER
    value: http://jenkins-master:8080/
  - name: DOCKER_HOST
    value: tcp://localhost:2375
  
jenkinsdockerslave:
  create: true
  name: jenkins-docker-slave
  image: docker:19.03-dind
  env:
    - name: DOCKER_TLS_CERTDIR
      value: ''
  securityContextContainer:
    privileged: true
  resources:
    limits:
      ephemeral-storage: "10Gi"
  volumeMounts:
    - name: host-tmp
      mountPath: /tmp
    - name: dind-storage
      mountPath: /var/lib/docker