# Default values for fint-adapter-arkiv.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
progressDeadlineSeconds: 600
revisionHistoryLimit: 10

onePasswordItem: 
  name: p360-arkiv-tffk
  create: true

environment:

image:
  repository: fintlabsacr.azurecr.io/p360-rpc-arkiv-adapter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: build.51

imagePullSecrets: []
nameOverride: adapter-p360-arkiv-tffk
fullnameOverride: ""

secretRef: p360-arkiv-tffk

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: "2"
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 1Gi

terminationMessagePath: 
terminationMessagePolicy: 
terminationGracePeriodSeconds: 

dnsPolicy: 
restartPolicy: 
schedulerName: 

volumeMounts:
  - mountPath: /temp
    name: tempdir

env:
  - {name: TZ, value: Europe/Oslo}
  - name: JAVA_TOOL_OPTIONS
    value: >-
      -Xmx1G -verbose:gc
      -XX:+ExitOnOutOfMemoryError
      -Dfile.encoding=UTF-8
  - {name: fint.adapter.endpoints.providers.kodeverk, value: https://api.felleskomponent.no/arkiv/kodeverk/provider}
  - {name: fint.adapter.endpoints.providers.noark, value: https://api.felleskomponent.no/arkiv/noark/provider}
  - {name: fint.adapter.endpoints.providers.samferdsel, value: https://api.felleskomponent.no/arkiv/samferdsel/provider}
  - {name: fint.adapter.endpoints.providers.kulturminne, value: https://api.felleskomponent.no/arkiv/kulturminnevern/provider}
  - {name: springfox.title, value: 'P360 RPC Adapter for Troms og Finnmark'}
  - {name: security.basic.enabled, value: 'false'}
  - {name: fint.adapter.reject-unknown-events, value: 'false'}
  - {name: fint.case.coding.dokumentType.B, value: '1'}
  - {name: fint.case.coding.filformat.RA-JPEG, value: 'JPG'}
  - {name: fint.case.coding.filformat.RA-PDF, value: 'PDF'}
  - {name: fint.case.coding.filformat.RA-TEKST, value: 'TXT'}
  - {name: fint.case.coding.filformat.RA-TIFF6, value: 'TIF'}
  - {name: fint.case.coding.journalposttype.I, value: '110'}
  - {name: fint.case.coding.journalposttype.N, value: '113'}
  - {name: fint.case.coding.journalposttype.S, value: '1'}
  - {name: fint.case.coding.journalposttype.U, value: '111'}
  - {name: fint.case.coding.journalposttype.X, value: '60005'}
  - {name: fint.case.coding.korrespondanseparttype.EA, value: '5'}
  - {name: fint.case.coding.korrespondanseparttype.EM, value: '6'}
  - {name: fint.case.defaults.drosjeloyve.tilgangsgruppe.journalpost, value: '200408'}
  - {name: fint.case.defaults.drosjeloyve.tilgangsgruppe.sak, value: '0'}
  - {name: fint.case.defaults.soknaddrosjeloyve.administrativEnhet, value: '200016'}
  - {name: fint.case.defaults.soknaddrosjeloyve.arkivdel, value: '200008'}
  - {name: fint.case.defaults.soknaddrosjeloyve.dokumentstatus, value: 'F'}
  - {name: fint.case.defaults.soknaddrosjeloyve.journalenhet, value: 'Sentralarkiv'}
  - {name: fint.case.defaults.soknaddrosjeloyve.journalstatus, value: 'M'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.1.ordning, value: 'Org.nr'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.1.tittel, value: '${organisasjonsnavn}' }
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.1.verdi, value: '${organisasjonsnummer}' }
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.2.ordning, value: Funksjonsbasert arkivnøkkel}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.2.verdi, value: '552'}
  - {name: fint.case.defaults.soknaddrosjeloyve.saksmappeType, value: 'Sak'}
  - {name: fint.case.defaults.soknaddrosjeloyve.saksstatus, value: 'B'}
  - {name: fint.case.defaults.soknaddrosjeloyve.title.cases, value: 'Drosjeløyve - ${organisasjonsnavn} - ${organisasjonsnummer}'}
  - {name: fint.case.defaults.soknaddrosjeloyve.saksansvarlig, value: '239802'}
  - {name: fint.case.defaults.soknaddrosjeloyve.saksbehandler, value: '239802'}
  - {name: fint.case.defaults.tilskuddfartoy.administrativEnhet, value: '200016'}
  - {name: fint.case.defaults.tilskuddfartoy.arkivdel, value: '60001'}
  - {name: fint.case.defaults.tilskuddfartoy.dokumentstatus, value: 'F'}
  - {name: fint.case.defaults.tilskuddfartoy.dokumentType, value: '1'}
  - {name: fint.case.defaults.tilskuddfartoy.journalenhet, value: 'Sentralarkiv'}
  - {name: fint.case.defaults.tilskuddfartoy.journalstatus, value: 'M'}
  - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.1.ordning, value: 'Funksjonsbasert arkivnøkkel'}
  - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.1.verdi, value: '800'}
  - {name: fint.case.defaults.tilskuddfartoy.saksansvarlig, value: '239803'}
  - {name: fint.case.defaults.tilskuddfartoy.saksbehandler, value: '239803'}
  - {name: fint.case.defaults.tilskuddfartoy.saksmappeType, value: 'Sak'}
  - {name: fint.case.defaults.tilskuddfartoy.saksstatus, value: 'B'}
  - {name: fint.case.defaults.tilskuddfartoy.tilknyttetRegistreringSom, value: 'H'}
  - {name: fint.case.defaults.tilskuddfartoy.title.cases, value: 'Riksantikvarens tilskudd til fartøyvern 2021 - ${kallesignal} - ${fartoyNavn} - ${kulturminneId}'}
  - {name: fint.case.defaults.tilskuddfartoy.title.records, value: '${soknadsnummer.identifikatorverdi} Tilskudd til fartøyvern ${kallesignal} - ${fartoyNavn} - ${kulturminneId}'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.administrativEnhet, value: '200016'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.arkivdel, value: '60001'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.dokumentstatus, value: 'F'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.dokumentType, value: '1'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.journalenhet, value: 'Sentralarkiv'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.journalstatus, value: 'M'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.1.ordning, value: 'Funksjonsbasert arkivnøkkel'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.1.verdi, value: '800'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksansvarlig, value: '239803'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksbehandler, value: '239803'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksmappeType, value: 'Sak'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksstatus, value: 'B'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.tilknyttetRegistreringSom, value: 'H'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.title.cases, value: 'Riksatikvarens tilskudd til kulturminner i privat eie - ${matrikkelnummer.gardsnummer}/${matrikkelnummer.bruksnummer} - ${bygningsnavn} - ${link$matrikkelnummer.kommunenummer#navn} kommune - ${kulturminneId}'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.title.records, value: 'Søknad om ${bygningsnavn} - ${matrikkelnummer.gardsnummer}/${matrikkelnummer.bruksnummer} - ${link$matrikkelnummer.kommunenummer#navn} kommune - ${kulturminneId}'}
  - {name: fint.p360.adcontextuser.account.digisak.username, value: 'svc_digisak@azure.tffk.no'}
  - {name: fint.p360.adcontextuser.account.drosjeloyve.username, value: 'svc_drosjeloyve@azure.tffk.no'}
  - {name: fint.p360.adcontextuser.casetype.default, value: 'drosjeloyve'}
  - {name: fint.p360.adcontextuser.casetype.soknaddrosjeloyve, value: 'drosjeloyve'}
  - {name: fint.p360.adcontextuser.casetype.tilskuddfartoy, value: 'digisak'}
  - {name: fint.p360.adcontextuser.casetype.tilskuddfredabygningprivateie, value: 'digisak'}
  - {name: fint.file-cache.directory, value: '/temp'}
  - {name: logging.level.no.fint.arkiv, value: 'info'}
  - {name: logging.level.no.fint.p360.data.p360, value: 'info'}
  - {name: logging.level.reactor.netty.http.client, value: 'warn'}
