apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullnameOverride}}
  labels:
    io.kompose.service: {{ .Values.fullnameOverride}}
spec:
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.fullnameOverride}}
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.fullnameOverride}}
    spec:
      containers:
        - name: {{ .Values.fullnameOverride}}
          image: {{ .Values.deployment.image}}/{{ .Values.fullnameOverride}}:{{ .Values.deployment.tag}}
          resources:
            limits:
              cpu: {{ .Values.deployment.resources.limits.cpu}}
              memory: {{ .Values.deployment.resources.limits.memory}}
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu}}
              memory: {{ .Values.deployment.resources.requests.memory}}
          ports:
            - containerPort: {{ .Values.deployment.ports}}
          readinessProbe:
            initialDelaySeconds: {{default 60 .Values.deployment.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{default 5 .Values.deployment.readinessProbe.timeoutSeconds}}
            httpGet:
              port: {{ .Values.deployment.readinessProbe.httpGet.port}}
              path: {{ .Values.deployment.readinessProbe.httpGet.path}}
          env:
            {{- range .Values.deployment.env }}
            - {name: {{ .name}}, value: {{ .value }}}
            {{- end }}   