apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride}}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    io.kompose.service: {{ .Values.fullnameOverride}}