# Default values for fint-adapter-arkiv.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
progressDeadlineSeconds: 600
revisionHistoryLimit: 10

onePasswordItem: 
  name: 
  create: false

environment:

image:
  repository: fintlabsacr.azurecr.io/p360-rpc-arkiv-adapter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: build.51

imagePullSecrets: []
nameOverride: adapter-p360-arkiv-ra
fullnameOverride: ""

secretRef: p360-rpc-arkiv-ra

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: "2"
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 1Gi

terminationMessagePath: 
terminationMessagePolicy: 
terminationGracePeriodSeconds:

dnsPolicy:
restartPolicy: 
schedulerName: 

volumeMounts:
  - mountPath: /temp
    name: tempdir

env:
  - {name: TZ, value: Europe/Oslo}
  - name: JAVA_TOOL_OPTIONS
    value: >-
      -Xmx1G -verbose:gc
      -XX:+ExitOnOutOfMemoryError
      -Dfile.encoding=UTF-8
  - {name: springfox.title, value: "Public 360 Online Adapter for Riksantikvaren"}
  - {name: security.basic.enabled, value: "false"}
  - {name: fint.adapter.organizations, value: ra.no}
  - {name: fint.adapter.reject-unknown-events, value: 'false'}
  - {name: fint.adapter.endpoints.providers.kodeverk, value: https://api.felleskomponent.no/arkiv/kodeverk/provider}
  - {name: fint.adapter.endpoints.providers.noark, value: https://api.felleskomponent.no/arkiv/noark/provider}
  - {name: fint.adapter.endpoints.providers.kulturminne, value: https://api.felleskomponent.no/arkiv/kulturminnevern/provider}
  - {name: fint.case.defaults.tilskuddfartoy.title.cases, value: '${kallesignal} - ${fartoyNavn} - Tilskudd - Kulturminne-ID ${kulturminneId} - Søknadsnr. ${soknadsnummer.identifikatorverdi}'}
  - {name: fint.case.defaults.tilskuddfartoy.field.CF_KulturminneID, value: '${kulturminneId}'}
  - {name: fint.case.defaults.tilskuddfartoy.saksmappeType, value: 'Sak'}
  - {name: fint.case.defaults.tilskuddfartoy.administrativEnhet, value: '200018'} # Seksjon for foto, arkiv og bibliotek
  - {name: fint.case.defaults.tilskuddfartoy.arkivdel, value: '200002'} # Digisak
  - {name: fint.case.defaults.tilskuddfartoy.saksstatus, value: 'B'}
  - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.1.ordning, value: 'Funksjonsbasert arkivnøkkel'}
  - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.1.verdi, value: 'recno:200074'}
  - {name: fint.case.defaults.tilskuddfartoy.noekkelord, value: ''}
  - {name: fint.case.defaults.tilskuddfartoy.korrespondansepartType, value: '5'}
  - {name: fint.case.defaults.tilskuddfartoy.journalpostType, value: '110'}
  - {name: fint.case.defaults.tilskuddfartoy.journalstatus, value: 'A'} # F eller M gir feilmelding
  - {name: fint.case.defaults.tilskuddfartoy.dokumentstatus, value: 'F'}
  - {name: fint.case.defaults.tilskuddfartoy.dokumentType, value: Brev}
  - {name: fint.case.defaults.tilskuddfartoy.tilknyttetRegistreringSom, value: H}
  - {name: fint.case.defaults.tilskuddfartoy.saksansvarlig, value: '200004' }
  - {name: fint.case.defaults.tilskuddfartoy.saksbehandler, value: '200004' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.title.cases, value: '${matrikkelnummer.gardsnummer}/${matrikkelnummer.bruksnummer} Tilskudd post 71 - Kulturminne-ID ${kulturminneId} - ${bygningsnavn} - Søknadsnr. ${soknadsnummer.identifikatorverdi}'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.field.CF_KulturminneID, value: '${kulturminneId}'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksmappeType, value: 'Sak'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.administrativEnhet, value: '200018'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.arkivdel, value: '200002'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksstatus, value: 'B'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.1.ordning, value: 'Funksjonsbasert arkivnøkkel'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.1.verdi, value: 'recno:200073'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.noekkelord, value: ''}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.korrespondansepartType, value: '5'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.journalpostType, value: '110'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.journalstatus, value: 'A'} # F eller M gir feilmelding
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.dokumentstatus, value: 'F'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.dokumentType, value: 'Brev'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.tilknyttetRegistreringSom, value: 'H'}
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksansvarlig, value: '200004' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksbehandler, value: '200004' }
  - {name: fint.case.coding.journalposttype.I, value: '110'}
  - {name: fint.case.coding.journalposttype.U, value: '111'}
  - {name: fint.case.coding.journalposttype.N, value: '113'}
  - {name: fint.case.coding.journalposttype.X, value: '60005'}
  - {name: fint.case.coding.journalposttype.S, value: '1'}
  - {name: fint.case.coding.korrespondanseparttype.EA, value: '5'}
  - {name: fint.case.coding.korrespondanseparttype.EM, value: '6'}
  - {name: fint.case.coding.filformat.RA-PDF, value: 'PDF'}
  - {name: fint.case.coding.filformat.RA-TEKST, value: 'TXT'}
  - {name: fint.case.coding.filformat.RA-JPEG, value: 'JPG'}
  - {name: fint.case.coding.filformat.RA-TIFF6, value: 'TIF'}
  - {name: logging.level.no.fint.p360.data.p360, value: info}
  - {name: logging.level.no.fint.p360.service, value: info}
  - {name: fint.file-cache.directory, value: '/temp'}
