# Default values for fint-adapter-faks.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: fintlabsacr.azurecr.io/fint-faks-adapter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 3.6.10-rc-2

volumes: []

volumeMounts: []

imagePullSecrets: []
nameOverride: adapter-faks-samediggi
fullnameOverride: ""

containerPort: 8091

secretRef: faks-adapter-samediggi

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  limits:
    memory: "2Gi"
    cpu: "2"
  requests:
    memory: "1Gi"
    cpu: "250m"

env:
  - {name: TZ, value: Europe/Oslo}
  - name: JAVA_TOOL_OPTIONS
    value: >-
      -Xmx1G -verbose:gc
      -XX:+ExitOnOutOfMemoryError
      -Dfile.encoding=UTF-8
  - {name: springfox.title, value: "SvarUt (Faks) Adapter for Samediggi / Sametinget"}
  - {name: security.basic.enabled, value: "false"}
  - {name: fint.adapter.reject-unknown-events, value: 'false'}
  - {name: fint.case.formats.title.tilskuddfartoy, value: 'Tilskudd - ${kallesignal} - ${fartoyNavn} - ${kulturminneId} - ${soknadsnummer.identifikatorverdi} - ${tittel}'}
  - {name: fint.case.formats.field.tilskuddfartoy.fartoy, value: '${kallesignal} ${fartoyNavn}' }
  - {name: fint.case.formats.field.tilskuddfartoy.soknadsnummer, value: '${soknadsnummer.identifikatorverdi}' }
  - {name: fint.case.formats.field.tilskuddfartoy.kulturminneid, value: '${kulturminneId}' }
  - {name: fint.case.formats.title.tilskuddfredabygningprivateie, value: 'Tilskudd - ${matrikkelnummer.gardsnummer}/${matrikkelnummer.bruksnummer} - ${bygningsnavn} - ${kulturminneId} - ${soknadsnummer.identifikatorverdi} - ${tittel}'}
  - {name: fint.case.formats.field.tilskuddfredabygningprivateie.matrikkel, value: '${matrikkelnummer.gardsnummer}/${matrikkelnummer.bruksnummer}' }
  - {name: fint.case.formats.field.tilskuddfredabygningprivateie.soknadsnummer, value: '${soknadsnummer.identifikatorverdi}' }
  - {name: fint.case.formats.field.tilskuddfredabygningprivateie.kulturminneid, value: '${kulturminneId}' }
  - {name: fint.internal-files.type, value: 'BLOB'}
  - {name: fint.internal-files.connection-string, valueFrom: {secretKeyRef: {name: stfint, key: connection-string}}}
  - {name: spring.data.mongodb.uri, valueFrom: {secretKeyRef: {name: fint-mongo-db, key: mongodb}}}
  - {name: spring.data.mongodb.database, value: 'svarut-faks'}
  - {name: fint.adapter.endpoints.providers.kodeverk, value: https://api.felleskomponent.no/arkiv/kodeverk/provider}
  - {name: fint.adapter.endpoints.providers.noark, value: https://api.felleskomponent.no/arkiv/noark/provider}
  - {name: fint.adapter.endpoints.providers.kulturminne, value: https://api.felleskomponent.no/arkiv/kulturminnevern/provider}
