apiVersion: v1
kind: Service
metadata:
  name: {{ include "fint-admin-portal-backend.name" . }}
  {{- with .Values.service.annotations }}
  annotations:
      {{- toYaml . | nindent 4  }}
    {{- end }}
  labels:
    {{- include "fint-admin-portal-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fint-admin-portal-backend.selectorLabels" . | nindent 4 }}
