apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name}} #drosjeloyve-service
spec:
  selector:
    matchLabels:
      app: {{ .Values.name}} #drosjeloyve-service
  strategy:
    type: RollingUpdate
    rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}  #drosjeloyve-service
    spec:
      containers:
        - name: {{ .Values.name}} #drosjeloyve-service
          image: {{ .Values.drosjeloyve.deployment.image.repository}}:{{ .Values.drosjeloyve.deployment.image.tag}} #fintlabsacr.azurecr.io/drosjeloyve:build.27
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
          envFrom:
            - secretRef:
                name: {{ .Values.name}} #drosjeloyve-service
          env:
          {{- range .Values.drosjeloyve.deployment.environments }}
            - {name: {{ .name}}, value: {{ .value }}}
          {{- end }} 
            