apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fint-altinn-download-queue-service.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "fint-altinn-download-queue-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "fint-altinn-download-queue-service.name" . }}
    spec:
      containers:
        - name: {{ include "fint-altinn-download-queue-service.name" . }}
          image: {{ .Values.deployment.repo}}/{{ .Values.deployment.image}}:{{ .Values.deployment.tag}}
          resources:
            limits:
              memory: {{ .Values.deployment.resources.limits.memory}}
              cpu: {{ .Values.deployment.resources.limits.cpu}}
            requests:
              memory: {{ .Values.deployment.resources.requests.memory}}
              cpu: {{ .Values.deployment.resources.requests.cpu}}
          ports:
            - containerPort: {{ .Values.deployment.ports.containerPort}}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.readinessProbe.path}}
              port: {{ .Values.deployment.readinessProbe.port}}
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds}}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds}}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.livenessProbe.path}}
              port: {{ .Values.deployment.livenessProbe.port}}
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds}}
            timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds}}
          envFrom:
            - secretRef:
                name: {{ include "fint-altinn-download-queue-service.name" . }}
          env:
            {{- range .Values.deployment.env }}
              - {name: {{ .name}}, value: {{ .value | toJson}}}
            {{- end }}
