apiVersion: v1
kind: Service
metadata:
  name: {{ include "fint-altinn-download-queue-service.name" . }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - {name: '{{ .Values.service.ports.name}}', port: {{ .Values.service.ports.port}}}
  selector:
    io.kompose.service: {{ include "fint-altinn-download-queue-service.name" . }}
