# Default values for vigobas-samtykke.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: vigobas-samtykke-viken
environment: beta
namespace: vigobas

service:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  ports:
     name: "80"
     port: 80
  type: LoadBalancer
    

deployment:
  namespace: vigobas
  annotations:
    onepwitempath: "vaults/aks-api-vault/items/samtykke-viken"
    onepwitemname: "samtykke-viken"
  replicas: 1
  minReadySeconds: 30
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    maxUnavailable: 0
    maxSurge: 1
  selector:
    matchLabels:
      io.kompose.service: vigobas-samtykke-viken
  template:
    metadata:
      labels:
        io.kompose.service: vigobas-samtykke-viken
    spec:
      restartPolicy: Always
      volumes:
        name: vigobas-samtykke-proxy
        configMap:
          name: vigobas-samtykke-proxy


frontend:
  image: fintlabsacr.azurecr.io/vigobas-samtykke-frontend:latest
  containerPort: 8000
  limits:
    cpu: "2"
    memory: "2Gi"
  requests:
    cpu: "250m"
    memory: "128Mi"

backend:
  image: fintlabsacr.azurecr.io/vigobas-samtykke-backend:build.${BUILD_NUMBER}_${GIT_COMMIT}
  secretRef:
    name: samtykke-viken
  containerPort: 9000
  limits:
    cpu: "2"
    memory: "2Gi"
  requests:
    cpu: "250m"
    memory: "128Mi"
  readinessProbe:
    path: /api/lb/test
    port: 9000
    timeoutSeconds: 5
  env:
  - {name: "fintcredentials__username", value: $(username)}
  - {name: "fintcredentials__password", value: $(password)}
  - {name: "fintcredentials__clientId", value: $(clientId)}
  - {name: "fintcredentials__openIdSecret", value: $(openIdSecret)}
  - {name: "fintcredentials__scope", value: $(scope)}
  - {name: "fintcredentials__idpUri", value: $(idpUri)}
  - {name: "fintcredentials__assetId", value: $(assetId)}
  - {name: "FintUri__FelleskomponentUri", value: "https://beta.felleskomponent.no/"}
  - {name: "Branding__default__logo", value: "01-viken.png"}
  - {name: "Branding__default__primaryColor", value: "#003b5c"}
  - {name: "Branding__default__primaryColorLight", value: "#99d6ea"}
  - {name: "Branding__default__secondaryColor", value: "#0085ca"}
  - {name: "Branding__default__featureColor1", value: "#006298"}
  - {name: "Branding__default__featureColor2", value: "#bbdde6"}
  - {name: "Branding__default__phoneNumber", value: "32300000"}
  - {name: "Branding__default__mail", value: "brukerhjelp@viken.no"}
  - {name: "Branding__default__countyName", value: "Viken Fylkeskommune"}
  
proxy:
  image: nginx:1.15
  limits:
    cpu: "500m"
    memory: "128Mi"
  containerPort: 80
  volumeMounts:
    mountPath: /etc/nginx/conf.d
    name: vigobas-samtykke-proxy
  env:
  - {name: TZ,  value: Europe/Oslo}