# Default values for fint-azure-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
minReadySeconds: 30
revisionHistoryLimit: 0

image:
  repository: fintlabsacr.azurecr.io/vigo-azure-ad-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: build.35

volumeMounts:
  - name: credentials
    mountPath: /credentials

volumes:
  - name: credentials
    secret:
      secretName: google-gmail-serviceaccount

nameOverride: vigo-azure-ad-service
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8080
  labels:
    io.kompose.service: vigo-azure-ad-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  selector:
    io.kompose.service: vigo-azure-ad-service

secretRef:
  name: vigo-azure-ad-service

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
limits:
  memory: "2Gi"
  cpu: "2"
requests:
  cpu: "100m"
  memory: "256Mi"

env:
  - {name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -XX:+UseG1GC -Xmx16G -verbose:gc'}
  - name: fint.invite.mail.serviceaccount
    value: '/credentials/serviceaccount.json'
  - name: fint.azure.qlik.allowed-domains
    value: rogfk.no,trondelagfylke.no,agderfk.no,viken.no,oslo.kommune.no,mrfylke.no,nfk.no,tffk.no,vlfk.no,vtfk.no,innlandetfylke.no,.vgs.no,osloskolen.no,ist.com
  - name: fint.azure.qlik.users.owner
    value: vigo_azure_manager@vigoiks.no
  - name: fint.azure.qlik.send-invitation
    value: "true"
  - name: fint.azure.qlik.synchronize-users
    value: "true"
  - name: fint.azure.qlik.dry-run
    value: "false"
  - name: fint.azure.qlik.user-delete
    value: "false"