#This is an example for a values.file to use for this library

replicaCount: 1
minReadySeconds: 30
revisionHistoryLimit: 10
progressDeadlineSeconds: 600

image:
  repository: fintlabsacr.azurecr.io/adapter-felles-kodeverk
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: build.14

imagePullSecrets: []
nameOverride: adapter-felles-kodeverk
fullnameOverride: ""

annotations:

onePasswordItem: 
  name: fake-adapter
  create: ture

environment: beta

labels:
  io.kompose.service: adapter-felles-kodeverk

initialDelaySeconds: 60
timeoutSeconds: 5

livenessProbe:
  
httpGetPath: /health

httpHeaders:

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

restartPolicy: Always

selector:
  io.kompose.service: adapter-felles-kodeverk

envFrom:

containerPort: 8091

volumeMounts:
  
volumes:

service:
  name:

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    memory: "2Gi"
    cpu: "2"
  requests:
    memory: "1Gi"
    cpu: "250m"

env:
  - name: TZ
    value: Europe/Oslo
  - name: JAVA_TOOL_OPTIONS
    value: '-XX:+ExitOnOutOfMemoryError -Xmx1G -verbose:gc'
  - name: springfox.title
    value: "Felles kodeverk Adapter"
  - name: fint.adapter.organizations
    value: fintlabs.no
  - name: fint.adapter.sse-endpoint
    value: https://beta.felleskomponent.no/felles/kodeverk/provider/sse/%s
  - name: fint.adapter.status-endpoint
    value: https://beta.felleskomponent.no/felles/kodeverk/provider/status
  - name: fint.adapter.response-endpoint
    value: https://beta.felleskomponent.no/felles/kodeverk/provider/response
  - name: fint.oauth.enabled
    value: "true"
  - name: fint.oauth.access-token-uri
    value: https://idp.felleskomponent.no/nidp/oauth/nam/token
  - name: fint.oauth.scope
    value: fint-client
  - name: fint.oauth.client-id
    valueFrom:
      secretKeyRef:
        key: client-id
        name: fake-adapter
  - name: fint.oauth.client-secret
    valueFrom:
      secretKeyRef:
        key: client-secret
        name: fake-adapter
  - name: fint.oauth.username
    valueFrom:
      secretKeyRef:
        key: username
        name: fake-adapter
  - name: fint.oauth.password
    valueFrom:
      secretKeyRef:
        key: password
        name: fake-adapter
  # - name: fint.adapter.ssb-klass.valid-to
  #   value: "2017-12-31"
  - name: fint.adapter.ssb-klass.interval
    value: "7200000"
