#This is an example for a values.file to use for this library

replicaCount: 1
minReadySeconds: 30
revisionHistoryLimit: 0
progressDeadlineSeconds:

image:
  repository: fintlabsacr.azurecr.io/fint-test-client
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: master.3

imagePullSecrets: []
nameOverride: test-client
fullnameOverride: ""

annotations:

labels:
  io.kompose.service: test-client

initialDelaySeconds: 30
timeoutSeconds: 5

livenessProbe:
  
httpGetPath:

httpHeaders:

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

restartPolicy: Always

selector:
  io.kompose.service: test-client

envFrom:

containerPort: 80

volumeMounts:
 

volumes:

service:
  name: 
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  selector:
    io.kompose.service: test-client

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    memory: "256Mi"
    cpu: "500m"
  requests:
    cpu: "100m"
    memory: "32Mi"

env:
  - name: TZ
    value: Europe/Oslo