# Default values for fint-events-azure-eventhub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

onePasswordVault: "aks-alpha-vault"
