apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fint-faks-adapter.name" . }}
  labels:
    {{- include "fint-faks-adapter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fint-faks-adapter.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fint-faks-adapter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8  }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            timeoutSeconds: 5
          {{- with .Values.volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12  }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretRef }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env: 
            {{- if .Values.env }}
                {{- toYaml .Values.env | nindent 12 }}
            {{- end }}