#This is an example for a values.file to use for this library

replicaCount: 1
minReadySeconds: 30
revisionHistoryLimit: 10
progressDeadlineSeconds: 600

image:
  repository: fintlabsacr.azurecr.io/reposilite
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: reposilite
fullnameOverride: ""

annotations:

onePasswordItem: 
  name: fint-portal-user
  create: ture

environment: beta 

labels:
  io.kompose.service: reposilite

initialDelaySeconds: 30
timeoutSeconds: 5

livenessProbe:
  
httpGetPath: /client/features

httpHeaders:

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

restartPolicy: Always

persistence:
  enabled: ture
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  storageClass:
  accessMode: ReadWriteOnce
  size: 5Gi

envFrom:
  - secretRef: 
      name: fint-portal-user

containerPort: 8080

volumeMounts:
  - mountPath: /data
    name: reposilite

volumes:
  - name: reposilite
    persistentVolumeClaim:
      claimName: reposilite

service:
  name: 
  type: LoadBalancer
  port: 8080
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  selector:
    io.kompose.service: reposilite

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    memory: "256Mi"
    cpu: "500m"
  requests:
    cpu: "100m"
    memory: "32Mi"

env:
  - {name: TZ, value: Europe/Oslo}
  - name: JAVA_TOOL_OPTIONS
    value: >-
      -Xmx64M
      -verbose:gc
      -XX:+ExitOnOutOfMemoryError
      -Dreposilite.port=8080
