apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "fint-jenkins.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fint-jenkins.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "fint-jenkins.selectorLabels" . | nindent 8 }}
      {{- with .Values.annotations }}
      annotations:
       {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
       {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.restartPolicy }}
      restartPolicy:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8  }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContextContainer }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports: 
            {{- with .Values.containerPort }}
              {{- toYaml . | nindent 12  }}
            {{- end }}
            {{- with .Values.containerPort2 }}
              {{- toYaml . | nindent 12  }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12  }}
          {{- end }}
          envFrom:
          {{- toYaml .Values.envFrom | nindent 12 }}
          env: 
            {{- if .Values.env }}
                {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
        {{- if .Values.jenkinsdockerslave.create }}
        - name: {{ .Values.jenkinsdockerslave.name }}
          image: {{ .Values.jenkinsdockerslave.image }}
          {{- if .Values.jenkinsdockerslave.env }}
          env:
            {{- toYaml .Values.jenkinsdockerslave.env | nindent 12 }}
          {{- end }}
          {{- with .Values.jenkinsdockerslave.securityContextContainer }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- toYaml .Values.jenkinsdockerslave.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.jenkinsdockerslave.resources | nindent 12 }}
        {{- end }}