
{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "fint-jenkins.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "fint-jenkins.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "fint-jenkins.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}