{{- define "fint-jenkins.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "fint-jenkins.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
      {{- toYaml . | nindent 4  }}
  {{- end }}
  creationTimestamp: null
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4  }}
  {{- end }}
  selector:
    {{- include "fint-jenkins.selectorLabels" . | nindent 4 }}
{{- end }}