# Default values for fint-altinn-ebevis-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "altinn-ebevis-service"

service:
  annotations: {service.beta.kubernetes.io/azure-load-balancer-internal: 'true'}
  type: LoadBalancer
  ports:
    name: '8080'
    port: 8080

deployment:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1, 
      maxUnavailable: 0
  volumes:
    name: credentials
    secretName: vigo-virksomhetssertifikat
  containers:
    repository: fint-altinn-ebevis-service
    image: fintlabsacr.azurecr.io
    tag: build.21
  volumeMounts:
    name: credentials
    mountPath: /credentials
  resources:
    limits:
      memory: "1000Mi"
      cpu: "500m"
    requests:
      memory: "500Mi"
      cpu: "250m"
    containerPort: 8080
  readinessProbe:
    path: /actuator/health/readiness
    port: 8080
    initialDelaySeconds: 30
    timeoutSeconds: 5
  livenessProbe:
    path: /actuator/health/liveness
    port: 8080
    initialDelaySeconds: 60
    timeoutSeconds: 5
  env:
    - {name: altinn.base-url, value: 'https://api.data.altinn.no/v1'}
    - {name: scheduling.initial-delay, value: '30000'}
    - {name: scheduling.fixed-delay, value: '60000'}
    - {name: altinn.key-store-file, value: '/credentials/vigo.p12'}