apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
 name: fint-events-azure-eventhub
 labels:
spec:
 itemPath: {{ include "fint-core-infra.onePasswordVaultPath" . }}/fint-events-azure-eventhub