# Default values for fint-sikri-arkiv-adapter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: 

onePasswordItem: 
  name: 
  create: 

environment:

annotations:
  prometheus.io/scrape: 
  prometheus.io/port: 
  prometheus.io/path: 

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

initialDelaySeconds: 90
timeoutSeconds: 5

volumes:
  - name: tempdir
    emptyDir:
      sizeLimit: 1G
volumeMounts:
  - name: tempdir
    mountPath: /temp

image:
  repository: 
  pullPolicy: 
  # Overrides the image tag whose default is the chart appVersion.
  tag: 

service:
  type: LoadBalancer
  port: 8080
  labels:
    io.kompose.service: admin-portal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"


secretRef: 
configMapRef: 

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  limits:
    memory: "5Gi"
    cpu: "2"
  requests:
    memory: "2Gi"
    cpu: "250m"

env:
  - {name: fint.betaling.invoice-update-rate, value: '1200000'}