# Default values for fint-adapter-sikri.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: adapter-sikri-arkiv-viken-no

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

image:
  repository: fintlabsacr.azurecr.io/sikri-arkiv-adapter:PR-38.29
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

volumes:
  - name: tempdir
    emptyDir:
      sizeLimit: 1G
volumeMounts:
  - name: tempdir
    mountPath: /temp
secretRef:
  name: viken-elements-adapter

service:
  type: ClusterIP
  port: 80

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
resources:
limits:
  memory: "2Gi"
  cpu: "2"
requests:
  memory: "1Gi"
  cpu: "250m"

env:
  - {name: TZ, value: Europe/Oslo}
  - name: JAVA_TOOL_OPTIONS
    value: >-
      -Xmx1G -verbose:gc
      -XX:+ExitOnOutOfMemoryError
      -Dfile.encoding=UTF-8
      -Dcom.sun.security.enableAIAcaIssuers=true
      -Dcom.sun.xml.ws.transport.http.client.HttpTransportPipe.dump=true
      -Dcom.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.dump=true
      -Dcom.sun.xml.ws.transport.http.HttpAdapter.dump=true
      -Dcom.sun.xml.internal.ws.transport.http.HttpAdapter.dump=true
      -Dcom.sun.xml.internal.ws.transport.http.HttpAdapter.dumpTreshold=5000
  - {name: springfox.title, value: "Elements Adapter for Viken"}
  - {name: security.basic.enabled, value: "false"}
  - {name: fint.adapter.endpoints.providers.kodeverk, value: https://beta.felleskomponent.no/arkiv/kodeverk/provider}
  - {name: fint.adapter.endpoints.providers.noark, value: https://beta.felleskomponent.no/arkiv/noark/provider}
  - {name: fint.adapter.endpoints.providers.kulturminne, value: https://beta.felleskomponent.no/arkiv/kulturminnevern/provider}
  - {name: fint.adapter.endpoints.providers.samferdsel, value: https://beta.felleskomponent.no/arkiv/samferdsel/provider}
  - {name: fint.adapter.reject-unknown-events, value: 'false'}
  - {name: fint.case.coding.format.RA-PDF, value: 'PDF'}
  - {name: fint.case.coding.format.RA-TEKST, value: 'TEXT'}
  - {name: fint.case.coding.format.RA-JPEG, value: 'JPEG'}
  - {name: fint.case.coding.format.RA-TIFF6, value: 'TIFF'}
  - {name: fint.case.defaults.soknaddrosjeloyve.title.cases, value: 'Drosjeløyve - ${organisasjonsnavn} - ${organisasjonsnummer}'}
  - {name: fint.case.defaults.soknaddrosjeloyve.administrativEnhet, value: '179'}
  - {name: fint.case.defaults.soknaddrosjeloyve.arkivdel, value: 'DLØYVE'}
  - {name: fint.case.defaults.soknaddrosjeloyve.journalenhet, value: 'VFRÅD'}
  - {name: fint.case.defaults.soknaddrosjeloyve.journalstatus, value: 'J'}
  - {name: fint.case.defaults.soknaddrosjeloyve.kKodeFagklasse, value: 'N12'}
  - {name: fint.case.defaults.soknaddrosjeloyve.kKodeTilleggskode, value: '&18'}
  - {name: fint.case.defaults.soknaddrosjeloyve.primarklassifikasjon, value: 'ORGNR'}
  - {name: fint.case.defaults.soknaddrosjeloyve.saksstatus, value: 'B'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.1.ordning, value: 'ORGNR'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.1.verdi, value: '${organisasjonsnummer}'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.1.tittel, value: '${organisasjonsnavn}'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.2.ordning, value: 'EMNE'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.2.verdi, value: 'N12'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.3.ordning, value: 'KTILLEGG'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.3.verdi, value: '&18'}
  - {name: fint.case.defaults.tilskuddfartoy.administrativEnhet, value: '64' }
  - {name: fint.case.defaults.tilskuddfartoy.arkivdel, value: SAK }
  - {name: fint.case.defaults.tilskuddfartoy.avskrivningsmaate, value: TE }
  - {name: fint.case.defaults.tilskuddfartoy.dokumentstatus, value: F }
  - {name: fint.case.defaults.tilskuddfartoy.dokumentType, value: ND }
  - {name: fint.case.defaults.tilskuddfartoy.journalenhet, value: VFRÅD }
  - {name: fint.case.defaults.tilskuddfartoy.journalpostType, value: I }
  - {name: fint.case.defaults.tilskuddfartoy.journalstatus, value: J } # M, F
  - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.1.ordning, value: 'EMNE' }
  - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.1.verdi, value: '243' }
  - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.2.ordning, value: 'FARTØY' }
  - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.2.tittel, value: '${fartoyNavn}' }
  - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.2.verdi, value: '${kallesignal}' }
  - {name: fint.case.defaults.tilskuddfartoy.korrespondansepartType, value: EA }
  - {name: fint.case.defaults.tilskuddfartoy.saksansvarlig, value: '287' }
  - {name: fint.case.defaults.tilskuddfartoy.saksbehandler, value: '287' }
  - {name: fint.case.defaults.tilskuddfartoy.saksmappeType, value: FARTØY }
  - {name: fint.case.defaults.tilskuddfartoy.saksstatus, value: B }
  - {name: fint.case.defaults.tilskuddfartoy.title.cases, value: '${kallesignal} - ${fartoyNavn} - ${soknadsnummer.identifikatorverdi} - Tilskudd Kapittel 1429 Post 74 og dispensasjoner' }
  - {name: fint.case.defaults.tilskuddfartoy.title.records, value: '#{tittel.replaceFirst("Tilskudd Kapittel.*","")}' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.administrativEnhet, value: '64' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.arkivdel, value: SAK }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.avskrivningsmaate, value: TE }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.dokumentstatus, value: F }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.dokumentType, value: ND }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.journalenhet, value: VFRÅD }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.journalpostType, value: I }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.journalstatus, value: J } # M, F
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.1.ordning, value: 'EMNE' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.1.verdi, value: 'C53' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.2.ordning, value: 'GBNR' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.2.tittel, value: '${matrikkelnummer.gardsnummer}/${matrikkelnummer.bruksnummer}' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.2.verdi, value: '${matrikkelnummer.gardsnummer}/${matrikkelnummer.bruksnummer}' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.korrespondansepartType, value: EA }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksansvarlig, value: '287' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksbehandler, value: '287' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksmappeType, value: FRIP }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksstatus, value: B }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.title.cases, value: '${link:matrikkelnummer.kommunenummer#navn} - ${matrikkelnummer.gardsnummer}/${matrikkelnummer.bruksnummer} - ${bygningsnavn} - ${kulturminneId} - Tilskudd Kapittel 1429 post 71 og dispensasjoner' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.title.records, value: '#{tittel.replaceFirst("Tilskudd Kapittel.*","")}' }
  - {name: fint.file-cache.directory, value: '/temp'}
  - {name: fint.sikri.identity.casetype.default, value: digisak }
  - {name: fint.sikri.identity.casetype.soknaddrosjeloyve, value: drosjeloyve }
  - {name: fint.sikri.identity.casetype.tilskuddfartoy, value: digisak }
  - {name: fint.sikri.identity.casetype.tilskuddfredabygningprivateie, value: digisak }
  - {name: fint.sikri.wsdl-location, value: /data }
  - {name: logging.level.no.fint.arkiv, value: trace}
  - {name: logging.level.no.fint.sikri, value: trace}
