# Default values for fint-adapter-sikri.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: adapter-sikri-arkiv-vlfk

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

image:
  repository: fintlabsacr.azurecr.io/sikri-arkiv-adapter:build.92
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

volumes:
  - name: tempdir
    emptyDir:
      sizeLimit: 1G
volumeMounts:
  - name: tempdir
    mountPath: /temp
secretRef:
  name: adapter-arkiv-vlfk

service:
  type: ClusterIP
  port: 80

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
resources:
limits:
  memory: "2Gi"
  cpu: "2"
requests:
  memory: "1Gi"
  cpu: "250m"

env:
  - {name: TZ, value: Europe/Oslo}
  - name: JAVA_TOOL_OPTIONS
    value: >-
      -Xmx1G -verbose:gc
      -XX:+ExitOnOutOfMemoryError
      -Dfile.encoding=UTF-8
      -Dcom.sun.security.enableAIAcaIssuers=true
      -Dcom.sun.xml.ws.transport.http.client.HttpTransportPipe.dump=true
      -Dcom.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.dump=true
      -Dcom.sun.xml.ws.transport.http.HttpAdapter.dump=true
      -Dcom.sun.xml.internal.ws.transport.http.HttpAdapter.dump=true
      -Dcom.sun.xml.internal.ws.transport.http.HttpAdapter.dumpTreshold=5000
  - {name: springfox.title, value: "Elements Adapter for Vestland"}
  - {name: security.basic.enabled, value: "false"}
  - {name: fint.adapter.endpoints.providers.kodeverk, value: https://beta.felleskomponent.no/arkiv/kodeverk/provider}
  - {name: fint.adapter.endpoints.providers.noark, value: https://beta.felleskomponent.no/arkiv/noark/provider}
  - {name: fint.adapter.endpoints.providers.kulturminne, value: https://beta.felleskomponent.no/arkiv/kulturminnevern/provider}
  - {name: fint.adapter.endpoints.providers.samferdsel, value: https://beta.felleskomponent.no/arkiv/samferdsel/provider}
  - {name: fint.adapter.reject-unknown-events, value: 'false'}
  - {name: fint.case.coding.format.RA-PDF, value: 'PDF' }
  - {name: fint.case.coding.format.RA-TEKST, value: 'TEXT' }
  - {name: fint.case.coding.format.RA-JPEG, value: 'JPEG' }
  - {name: fint.case.coding.format.RA-TIFF6, value: 'TIFF' }
  - {name: fint.case.coding.journalposttype.I, value: 'I'}
  - {name: fint.case.coding.journalposttype.N, value: 'N'}
  - {name: fint.case.coding.journalposttype.S, value: 'S'}
  - {name: fint.case.coding.journalposttype.U, value: 'U'}
  - {name: fint.case.coding.journalposttype.X, value: 'X'}
  - {name: fint.case.coding.saksstatus.A, value: 'A'}
  - {name: fint.case.coding.saksstatus.B, value: 'B'}
  - {name: fint.case.coding.tilknyttetRegistreringSom.H, value: 'H'}
  - {name: fint.case.coding.tilknyttetRegistreringSom.V, value: 'V'}
  - {name: fint.case.defaults.soknaddrosjeloyve.title.cases, value: 'Drosjeløyve - ${organisasjonsnavn} - ${organisasjonsnummer}'}
  - {name: fint.case.defaults.soknaddrosjeloyve.administrativEnhet, value: '9'}
  - {name: fint.case.defaults.soknaddrosjeloyve.arkivdel, value: 'DROSJE'}
  - {name: fint.case.defaults.soknaddrosjeloyve.journalenhet, value: 'VLFKJ'}
  - {name: fint.case.defaults.soknaddrosjeloyve.journalstatus, value: 'J'}
  - {name: fint.case.defaults.soknaddrosjeloyve.kKodeFagklasse, value: 'N12'}
  - {name: fint.case.defaults.soknaddrosjeloyve.kKodeTilleggskode, value: '&18'}
  - {name: fint.case.defaults.soknaddrosjeloyve.primarklassifikasjon, value: 'ORG'}
  - {name: fint.case.defaults.soknaddrosjeloyve.saksstatus, value: 'B'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.1.ordning, value: 'ORG'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.1.verdi, value: '${organisasjonsnummer}'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.1.tittel, value: '${organisasjonsnavn}'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.2.ordning, value: 'EMNE'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.2.verdi, value: 'N12'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.3.ordning, value: 'KTILLEGG'}
  - {name: fint.case.defaults.soknaddrosjeloyve.klassifikasjon.3.verdi, value: '&18'}
  - {name: fint.case.defaults.tilskuddfartoy.administrativEnhet, value: '5' }
  - {name: fint.case.defaults.tilskuddfartoy.arkivdel, value: KULTM }
  #            - {name: fint.case.defaults.tilskuddfartoy.dokumentstatus, value: F }
  #            - {name: fint.case.defaults.tilskuddfartoy.dokumentType, value: ND }
  - {name: fint.case.defaults.tilskuddfartoy.journalenhet, value: 'VLFKJ' }
  #            - {name: fint.case.defaults.tilskuddfartoy.journalpostType, value: T } # I
  - {name: fint.case.defaults.tilskuddfartoy.journalstatus, value: J } # M, F
  - {name: fint.case.defaults.tilskuddfartoy.avskrivningsmaate, value: TE }
  - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.1.ordning, value: 'KULTMID' }
  - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.1.verdi, value: '${kulturminneId}' }
  - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.1.tittel, value: '${fartoyNavn}' }
  #            - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.1.ordning, value: 'EMNE' }
  #            - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.1.verdi, value: '243' }
  #            - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.2.ordning, value: 'FARTØY' }
  #            - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.2.tittel, value: '${fartoyNavn}' }
  #            - {name: fint.case.defaults.tilskuddfartoy.klassifikasjon.2.verdi, value: '${kallesignal}' }
  #            - {name: fint.case.defaults.tilskuddfartoy.korrespondansepartType, value: EA }
  - {name: fint.case.defaults.tilskuddfartoy.saksansvarlig, value: '144' }
  - {name: fint.case.defaults.tilskuddfartoy.saksbehandler, value: '144' }
  - {name: fint.case.defaults.tilskuddfartoy.saksmappeType, value: 'TS' }
  - {name: fint.case.defaults.tilskuddfartoy.saksstatus, value: B }
  - {name: fint.case.defaults.tilskuddfartoy.title.cases, value: 'Fartøy - ${fartoyNavn} - ${kulturminneId}' }
  #            - {name: fint.case.defaults.tilskuddfartoy.title.records, value: '#{tittel.replaceFirst("Tilskudd Kapittel.*","")}' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.administrativEnhet, value: '5' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.arkivdel, value: KULTM }
  #            - {name: fint.case.defaults.tilskuddfredabygningprivateie.dokumentstatus, value: F }
  #            - {name: fint.case.defaults.tilskuddfredabygningprivateie.dokumentType, value: ND }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.journalenhet, value: 'VLFKJ' }
  #            - {name: fint.case.defaults.tilskuddfredabygningprivateie.journalpostType, value: T } # I
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.journalstatus, value: J } # M, F
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.avskrivningsmaate, value: TE }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.1.ordning, value: 'KULTMID' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.1.verdi, value: '${kulturminneId}' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.1.tittel, value: '${bygningsnavn}' }
  #            - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.2.ordning, value: 'GBNR' }
  #            - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.2.tittel, value: '${matrikkelnummer.gardsnummer}/${matrikkelnummer.bruksnummer}' }
  #            - {name: fint.case.defaults.tilskuddfredabygningprivateie.klassifikasjon.2.verdi, value: '${matrikkelnummer.gardsnummer}/${matrikkelnummer.bruksnummer}' }
  #            - {name: fint.case.defaults.tilskuddfredabygningprivateie.korrespondansepartType, value: EA }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksansvarlig, value: '144' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksbehandler, value: '144' }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksmappeType, value: TS }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.saksstatus, value: B }
  - {name: fint.case.defaults.tilskuddfredabygningprivateie.title.cases, value: 'Bygg - ${bygningsnavn} - ${kulturminneId}' }
  #            - {name: fint.case.defaults.tilskuddfredabygningprivateie.title.records, value: '#{tittel.replaceFirst("Tilskudd Kapittel.*","")}' }
  - {name: fint.file-cache.directory, value: '/temp'}
  - {name: fint.sikri.identity.casetype.default, value: digisak }
  - {name: fint.sikri.identity.casetype.soknaddrosjeloyve, value: drosjeloyve }
  - {name: fint.sikri.identity.casetype.tilskuddfartoy, value: digisak }
  - {name: fint.sikri.identity.casetype.tilskuddfredabygningprivateie, value: digisak }
  - {name: fint.sikri.variantformat, value: P }
  - {name: fint.sikri.wsdl-location, value: /data }
  - {name: fint.sikri.skip-internal-contacts, value: 'true' }
