# Default values for fint-altinn-download-queue-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
nameOverride: altinn-downloadqueue-service

service: 
  annotations: {service.beta.kubernetes.io/azure-load-balancer-internal: 'true'}
  type: LoadBalancer
  ports:
    name: '8080'
    port: 8080
 
deployment:
  repo: fintlabsacr.azurecr.io
  image: fint-altinn-download-queue-service
  tag: build.12
  resources:
    limits:
      memory: "1000Mi"
      cpu: "500m"
    requests:
      memory: "500Mi"
      cpu: "250m"
  ports:
    containerPort: 8080
  readinessProbe:
    path: /actuator/health/readiness
    port: 8080
    initialDelaySeconds: 30
    timeoutSeconds: 5
  livenessProbe:
    path: /actuator/health/liveness
    port: 8080
    initialDelaySeconds: 60
    timeoutSeconds: 5
  env:
    - {name: altinn.download-queue-uri, value: 'https://www.altinn.no/ArchiveExternal/DownloadQueueExternalBasic.svc'}
    - {name: altinn.attachment-data-streamed-uri, value: 'https://www.altinn.no/ArchiveExternal/ServiceOwnerArchiveExternalStreamedBasic.svc'}
    - {name: altinn.attachment-data-streamed-uri, value: 'https://www.altinn.no/ArchiveExternal/ServiceOwnerArchiveExternalStreamedBasic.svc'}
    - {name: scheduling.initial-delay, value: '10000'}
    - {name: scheduling.fixed-delay, value: '60000'}